name: Dynmap-SimpleClans
main: net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans
description: SimpleClans addon for Dynmap
version: '${project.version}'

authors: [ phaed, BangL ]
softdepend: [ dynmap, SimpleClans ]

commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again

permissions:
  simpleclans.map.toggle:
    description: Can toggle map visibility
